global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'permissions-api'
    static_configs:
      - targets: 
          - 'host.docker.internal:9091'
        labels:
          service: 'permissions-api'

  - job_name: 'proxy'
    static_configs:
      - targets:
          - 'host.docker.internal:9092'
        labels:
          service: 'proxy'

